### ISSUE TITLE
Please create your GITHUB account to ask any question.

### ISSUE THREAD

**Issue by tkimva** [tkimva/ucr-eecs168#1]
Hi EECS168 students in Winter 2016,

You might be familiar with PIAZZA system to communicate with TA and professor for the class. But PIAZAA doesn't have any function to share the files, so we will use GITHUB to share questions and files as well. Please register github and use this. 

Thanks
Taeyoung

**Comment by anguy094** [comment]
Hi,

I was just wondering, are we still expected to attend lab today? I didn't quite understand what the email was saying about lab. Sorry for the repetition.

Thank you,
Andy

**Comment by tkimva** [comment]
Hi Andy,

Officially, we are not going to do any lab today and Thursday.

As we use ENGR linux system for this lab, If you have any background for remote linux server and ENGR (bender, storm) connection, then you don't need to come. 

If this is first time to use SSH and X11 to ENGR systems, I highly recommend to come to pre-lab today , it will give you a solid and easy start for next week lab.

I don't check any attendance this week.

Thanks,
Taeyoung

**Comment by isaaclino** [comment]
Hello: I follow all the instructions for lab0 and I can log in with no problem, I can see the welcome message "Welcome to Storm" to "but I type "cdesigner&" I got the following error: " Error: DISPLAY environment variable is not defined."
I am using my mac and remotely accessing from home, is that a problem?

**Comment by AdelekeInc** [comment]
Hello Issac,

I also use a Mac when remotely connecting to storm. The Mac is not the issue, the operating system probably is. Apple stopped supporting X11, their default X Window System interface, back in 2012 with OS X 10.8 Mountain Lion. The support has moved from X11 to XQuartz. You can use XQuartz on your computer to view the Synopsys Galaxy Custom Designer. You can download it here: http://www.xquartz.org. Once it installs you will need to log out and log back into your computer. 

I am running OS X 10.11.2 El Capitan on a 2009 MacBook Pro. Please let me know if you have any other questions. I hope this helps!

Sincerely,
Dayo Adeleke

**Comment by tkimva** [comment]
@isaaclino Hi Issac, yes you need to install Xquartz in OS X to use Xserver as Apple didn't continue Windows app a few years ago. You need to download Xwindows app from http://www.xquartz.org as Dayo answered to use your own computer. 

@AdelekeInc Thanks, Dayo for right answer.

Taeyoung

**Comment by isaaclino** [comment]
Thanks, it works!
