### ISSUE TITLE
Downloading files from storm server at home.

### ISSUE THREAD

**Issue by tkimva** [tkimva/ucr-eecs168#10]
See this,

http://systems.engr.ucr.edu/tutorials/homedirectory.html

you need to use ENGR VPN to use above.

Thanks,
Taeyoung

**Comment by opeope** [comment]
Vpn link on the page is broken
here is the link to get the engr vpn
http://systems.engr.ucr.edu/vpn/vpninstall.html

**Comment by tkimva** [comment]
This link is working now for me. If you have problem to use vpn the you can use sftp with filezilla to connect storm server to file transfer without vpn.
