### ISSUE TITLE
for someone who still have difficulty with testbench of NAND circuit for your lab1.

### ISSUE THREAD

**Issue by tkimva** [tkimva/ucr-eecs168#11]
Refer this screenshot
![screen shot 2016-01-26 at 10 59 23 pm](https://cloud.githubusercontent.com/assets/993376/12606225/6da28408-c480-11e5-8726-14ba43a56a89.png)
For two outputs,
you can put two vpluses (10ns period, 20ns period).
Hope this can help your lab report.

**Comment by AdelekeInc** [comment]
Hello Taeyoung,

I am not sure what is wrong but I cannot netlist and run my NAND_testbench. I am including screenshots below of my schematic and my results to the console and from the netlist. One of the errors I am getting says:

 "**warning** (input.spi:25) Parameter  nf is ignored
  **error** (input.spi:25) Definition of model/subckt "p12" is not found for the element "m19". Please specify a defined model/subckt name."

I am not sure how to go about defining the name and I was unable to find anything when I tried to search for a solution online. 

**NAND Schematic**
![screen shot 2016-01-29 at 8 11 06 pm](https://cloud.githubusercontent.com/assets/9289687/12693649/d222921a-c6c4-11e5-8ff7-58d69e7ca70d.png)

**NAND Symbol**
![screen shot 2016-01-29 at 8 11 17 pm](https://cloud.githubusercontent.com/assets/9289687/12693646/d21b8d80-c6c4-11e5-81ca-1bf18632363d.png)

**NAND Testbench**
![screen shot 2016-01-29 at 8 11 27 pm](https://cloud.githubusercontent.com/assets/9289687/12693648/d21ea128-c6c4-11e5-899b-db814ff20ea1.png)

**Console Output**
![screen shot 2016-01-29 at 8 10 19 pm](https://cloud.githubusercontent.com/assets/9289687/12693647/d21d4d32-c6c4-11e5-95b7-20f68312471a.png)

**Netlist Error**
![screen shot 2016-01-29 at 8 10 41 pm](https://cloud.githubusercontent.com/assets/9289687/12693645/d2171f02-c6c4-11e5-9341-d7df923121de.png)

Please let me know if you have any questions.

- Dayo Adeleke

**Comment by tkimva** [comment]
in your netlist, M19 PMOS and M20 NMOS are wrongly set the Width.
M19 PMOS should be 0.5um not .5um. If you omit zero (0) for sizing (W or L), HSPICE simulation does not understand your parameter setting for transistor.
M20 PMOS should be 0.25um not .25um. The same reason. Please fix your parameter with correct number.

Also, in SAE, check your setup -> model files and correctly set your HSPICE sim file for 90nm as seen in lab1.

**Comment by AdelekeInc** [comment]
Taeyoung,

I made the changes you mentioned above. The main issue that I had was not changing the section to "TT_12" I had set correct path just not the section. 

Thank you for your help!

- Dayo Adeleke

**Comment by tkimva** [comment]
yes, as I mentioned, setup-> model files should be correctly setup. TT_12 Not BJT_12. Good to know. Thanks

**Comment by Jun-Jun** [comment]
I accidently turned in a tar file of the lab...Also thanks again for taking
the time to help me fix my problem regarding the lab.

On Fri, Jan 29, 2016 at 8:57 PM, Taeyoung Kim <notifications@github.com>
wrote:

> yes, as I mentioned, setup-> model files should be correctly setup. TT_12
> Not BJT_12. Good to know. Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tkimva/ucr-eecs168/issues/11#issuecomment-177067478>.
>



-- 
John Galo
Email: jgalo001@ucr.edu
University of California, Riverside
Undergraduate Student, Electrical Engineer

**Comment by tkimva** [comment]
tar.gz tar tgz gz , it should be as long as I can uncompress for grading.
