### ISSUE TITLE
Error when running SAE

### ISSUE THREAD

**Issue by AbrahamAMartinez** [tkimva/ucr-eecs168#12]
I continue getting this error and am unsure of what I am doing incorrectly.

![error message](https://cloud.githubusercontent.com/assets/16658134/12694583/1e34aab8-c6e7-11e5-993a-64d7340faaed.jpg)

![nand symbol](https://cloud.githubusercontent.com/assets/16658134/12694600/7190bd64-c6e7-11e5-879e-199d86646fa3.jpg)

**Comment by tkimva** [comment]
I cannot see your image. 
So far, I saw at least more than 15 people's problems, but most of problems were happened as they didn't correctly follow tutorial. If your circuit was correct with correct vpulse, vsource and HSPICE spice model file was correctly set, then your simulation should be fine. Please review the tutorial as your lab report deadline is Monday night.

**Comment by AbrahamAMartinez** [comment]
![screen shot 2016-01-30 at 12 40 37 am](https://cloud.githubusercontent.com/assets/16658134/12694672/35f8aaa2-c6ea-11e5-93de-a3c1e72f1420.jpeg)


Please let me know if you cannot see the image again. My issue seems to involve something having to do with the symbol.

**Comment by tkimva** [comment]
There is no symbol error. Symbol error comes from your wrong circuit. You need to take a look at your analog instances in your circuit. Also wire naming with PIN as well. Don't manually assign PIN name. PIN names are always automatically assigned from wire name.
