### ISSUE TITLE
SOS

### ISSUE THREAD

**Issue by Duyiming** [tkimva/ucr-eecs168#14]
![1](https://cloud.githubusercontent.com/assets/16651661/12721599/7b64b74e-c8b5-11e5-9b09-412209c605f2.png)

Why it shows like this? I don't know what's wrong.

**Comment by tkimva** [comment]
Your simulation result already explicitly explained what was wrong.
In testbench schematic, B pulse (`vpulse`) setting was correct but A pulse was wrongly assigned for period. Please see the `vpulse` parameter of A input by using property editor. Go to lab1 tutorial and see Fig 19. Compare this settings with yours then you will see what was wrong. You need to understand first what are `pulse width` and `period` in a pulse signal.
