### ISSUE TITLE
Busses

### ISSUE THREAD

**Issue by blu006** [tkimva/ucr-eecs168#17]
Hello,

Sorry for all the questions.  I hope nobody's email inbox is getting filled.

Should we / do we need to use busses for the 4 bit adder?

I can't find any online documentation on how to use busses within the schematic editor.

-- Brandon

**Comment by tkimva** [comment]
Please take a look the announcement. I will give some hint for 1-bit adder first and 4bit adder soon. Please hold on by next lab.
