### ISSUE TITLE
Issue logging in via Putty

### ISSUE THREAD

**Issue by schau009** [tkimva/ucr-eecs168#24]
Everytime I put cdesigner& it gives me this error:

cdesigner: cannot connect to X server localhost:20.0

How can I fix this?

**Comment by MehranGhamaty** [comment]
have you enabled x11 in the putty settings and have Xming running?

**Comment by schau009** [comment]
I figured it out, thank you anyways.

**Comment by Biggiesmurf** [comment]
Try 
localhost:0.0
