### ISSUE TITLE
LVS violation error

### ISSUE THREAD

**Issue by kdeme001** [tkimva/ucr-eecs168#25]
For my 1bit Full adder LVS run i ran into a violation but i do not know what it means
![image](https://cloud.githubusercontent.com/assets/5580323/12969373/66c4e06c-d034-11e5-8a7a-d5cf39cdd37e.png)

in LVS it says this
Extraction Errors
![image](https://cloud.githubusercontent.com/assets/5580323/12969399/b41cfae8-d034-11e5-8f19-2ba082c45ac5.png)

**Comment by tkimva** [comment]
Sovled.
