### ISSUE TITLE
just a small typo

### ISSUE THREAD

**Issue by ifuka001** [tkimva/ucr-eecs168#33]
For the what to submit section in week4 it says:

Lab report (PDF format)
file name should be following

lab3-[My UCR NET ID].pdf

but should be lab4-[My UCR NET ID].pdf

nothing really important but just wanted to let you know. Was nice having you Taeyoung

**Comment by tkimva** [comment]
yes, 

It's typo in tutorial, it should be lab4 not lab3 for the filename, which doesn't really matter though. I fixed minor typo. 

It was great for me to help you guys.

Thanks,
Taeyoung
