### ISSUE TITLE
Software Install

### ISSUE THREAD

**Issue by AbrahamAMartinez** [tkimva/ucr-eecs168#7]
Where can I find the link to download the software (OS X) needed for the lab?

**Comment by tkimva** [comment]
#1 Please refer Dayo's comment. For OSX, you just need to download and install Xquartz for Xwindows. After opening terminal, you can use `ssh` command as explained in our pre-lab.

**Comment by tkimva** [comment]
If you still have some issues, please come by TA office hour tomorrow 11am-12pm at WCH109.
